<?php

namespace RptGen\Report\Dcasp;

use DateTime;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use RptGen\Db;

/**
 * DCASP - Palanço Patrimonial - quadro do superávit/déficit financeiro
 *
 * @author Everton
 */
final class BpQSuperavitFinanceiro extends DcaspBase {

    public function __construct(Db $con, Spreadsheet $spreadsheet, int $remessa, string $escopo) {
        parent::__construct('BP Q3', $con, $spreadsheet, $remessa, $escopo);
    }

    public function run(): void {
        printf("\t-> gerando planilha %s" . PHP_EOL, $this->sheetName);

        $sheet = $this->spreadsheet->setActiveSheetIndexByName($this->sheetName);

        foreach ($this->getCellMap() as $cellAddress => $cellValue) {
            $sheet->setCellValue($cellAddress, $cellValue);
        }
    }

    protected function getCellMap(): array {
        return [
            'D11' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 500),
            'D12' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 501),
            'D13' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 502),
            'D14' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 540),
            'D15' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 541),
            'D16' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 542),
            'D17' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 543),
            'D18' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 544),
            'D19' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 550),
            'D20' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 551),
            'D21' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 552),
            'D22' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 553),
            'D23' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 569),
            'D24' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 570),
            'D25' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 571),
            'D26' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 572),
            'D27' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 573),
            'D28' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 574),
            'D29' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 575),
            'D30' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 576),
            'D31' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 599),
            'D32' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 600),
            'D33' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 601),
            'D34' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 602),
            'D35' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 603),
            'D36' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 604),
            'D37' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 605),
            'D38' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 621),
            'D39' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 622),
            'D40' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 631),
            'D41' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 632),
            'D42' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 633),
            'D43' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 634),
            'D44' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 635),
            'D45' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 636),
            'D46' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 659),
            'D47' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 660),
            'D48' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 661),
            'D49' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 662),
            'D50' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 665),
            'D51' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 669),
            'D52' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 700),
            'D53' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 701),
            'D54' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 702),
            'D55' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 703),
            'D56' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 704),
            'D57' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 705),
            'D58' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 706),
            'D59' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 707),
            'D60' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 708),
            'D61' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 709),
            'D62' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 710),
            'D63' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 711),
            'D64' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 712),
            'D65' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 713),
            'D66' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 714),
            'D67' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 715),
            'D68' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 716),
            'D69' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 717),
            'D70' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 718),
            'D71' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 719),
            'D72' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 749),
            'D73' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 750),
            'D74' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 751),
            'D75' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 752),
            'D76' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 753),
            'D77' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 754),
            'D78' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 755),
            'D79' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 756),
            'D80' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 757),
            'D81' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 758),
            'D82' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 759),
            'D83' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 760),
            'D84' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 761),
            'D85' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 799),
            'D86' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 800),
            'D87' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 801),
            'D88' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 802),
            'D89' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 803),
            'D90' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 860),
            'D91' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 861),
            'D92' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 862),
            'D93' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 869),
            'D94' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 880),
            'D95' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 898),
            'D96' => $this->readSql('dcasp/bp/q3/DDRSaldoAtual', $this->consolidado, $this->remessa, $this->entidades, 899),
            
            'E11' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 500),
            'E12' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 501),
            'E13' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 502),
            'E14' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 540),
            'E15' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 541),
            'E16' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 542),
            'E17' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 543),
            'E18' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 544),
            'E19' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 550),
            'E20' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 551),
            'E21' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 552),
            'E22' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 553),
            'E23' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 569),
            'E24' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 570),
            'E25' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 571),
            'E26' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 572),
            'E27' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 573),
            'E28' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 574),
            'E29' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 575),
            'E30' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 576),
            'E31' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 599),
            'E32' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 600),
            'E33' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 601),
            'E34' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 602),
            'E35' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 603),
            'E36' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 604),
            'E37' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 605),
            'E38' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 621),
            'E39' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 622),
            'E40' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 631),
            'E41' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 632),
            'E42' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 633),
            'E43' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 634),
            'E44' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 635),
            'E45' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 636),
            'E46' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 659),
            'E47' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 660),
            'E48' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 661),
            'E49' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 662),
            'E50' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 665),
            'E51' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 669),
            'E52' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 700),
            'E53' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 701),
            'E54' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 702),
            'E55' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 703),
            'E56' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 704),
            'E57' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 705),
            'E58' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 706),
            'E59' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 707),
            'E60' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 708),
            'E61' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 709),
            'E62' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 710),
            'E63' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 711),
            'E64' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 712),
            'E65' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 713),
            'E66' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 714),
            'E67' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 715),
            'E68' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 716),
            'E69' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 717),
            'E70' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 718),
            'E71' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 719),
            'E72' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 749),
            'E73' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 750),
            'E74' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 751),
            'E75' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 752),
            'E76' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 753),
            'E77' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 754),
            'E78' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 755),
            'E79' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 756),
            'E80' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 757),
            'E81' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 758),
            'E82' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 759),
            'E83' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 760),
            'E84' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 761),
            'E85' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 799),
            'E86' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 800),
            'E87' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 801),
            'E88' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 802),
            'E89' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 803),
            'E90' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 860),
            'E91' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 861),
            'E92' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 862),
            'E93' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 869),
            'E94' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 880),
            'E95' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 898),
            'E96' => $this->readSql('dcasp/bp/q3/DDRSaldoAnterior', $this->consolidado, $this->remessa, $this->entidades, 899),
        ];
    }
}
