SELECT
	(SELECT SUM(SALDO_INICIAL)::decimal
		FROM PAD.BVER_ENC%s
		WHERE REMESSA = %d
			AND ENTIDADE IN %s
			AND ESCRITURACAO like 'S'
			AND (CONTA_CONTABIL like '21%%'
				OR CONTA_CONTABIL like '22%%')
			AND INDICADOR_SUPERAVIT_FINANCEIRO like 'F' ) +
	(SELECT SUM(SALDO_INICIAL_NAO_PROCESSADO)::decimal
		FROM PAD.RESTOS_PAGAR%s
		WHERE REMESSA = %d
			AND ENTIDADE IN %s )