SELECT
	(SELECT SUM(SALDO_ATUAL)::decimal
		FROM PAD.BVER_ENC%s
		WHERE REMESSA = %d
			AND ENTIDADE IN %s
			AND ESCRITURACAO like 'S'
			AND (CONTA_CONTABIL like '21%%'
				OR CONTA_CONTABIL like '22%%')
			AND INDICADOR_SUPERAVIT_FINANCEIRO like 'F' ) +
	(SELECT SUM(SALDO_FINAL_NAO_PROCESSADO)::decimal
		FROM PAD.RESTOS_PAGAR%s
		WHERE REMESSA = %d
			AND ENTIDADE IN %s ) +
	(SELECT SUM(EMPENHADO_A_LIQUIDAR)::decimal
		FROM PAD.BAL_DESP%s
		WHERE REMESSA = %d
			AND ENTIDADE IN %s )